name    'ispavailability-bucky'
version '0.0.2'
source 'https://github.com/electrical/puppet-bucky'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring bucky'
description 'Module for managing and configuring bucky'
project_page 'https://github.com/electrical/puppet-bucky'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
