name    'mrsecure-bucky2'
version '0.2.1'
source 'git clone https://github.com/mrsecure/puppet-bucky2.git'
author 'mrsecure'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring bucky2'
description 'Module for managing and configuring bucky2'
project_page 'https://github.com/mrsecure/puppet-bucky2'
dependency 'puppetlabs/stdlib', '>= 3.0.0'

