name    'mrsecure-bucky'
version '0.4.0'
source 'git clone https://github.com/mrsecure/puppet-bucky.git'
author 'mrsecure'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring bucky'
description 'Module for managing and configuring bucky'
project_page 'https://github.com/mrsecure/puppet-bucky'
dependency 'puppetlabs/stdlib', '>= 3.0.0'

